ci(swiftlint): add in swiftlinter
Pocket/pocket-ios pull request #228
Opened 2022-08-24 16:40 UTC by bassrock

## Summary
* Follow the mozila ios engineering swiftlint rules that are being adopted.

## References 
* Links to docs, tickets, designs if available

## Implementation Details
* Overview of work that was implemented and changes made to the codebase

## Test Steps
* Write out what QA should do to verify this change works as expected and hasn't introduced regressions. Can mention specific OS versions, devices, areas of the app to test as needed.

## PR Checklist:
- [ ] Added Unit / UI tests
- [ ] Self Review (review, clean up, documentation, run tests)
- [ ] Basic Self QA

## Screenshots

2022-08-25 13:53 UTC, cyndichin reviewed
thanks Daniel! as mentioned in a couple of other PRs, we may want to add https://realm.github.io/SwiftLint/multiline_arguments_brackets.html
I'll check with Firefox team to see what they think too

https://github.com/Pocket/pocket-ios/pull/227#discussion_r954098412

2022-08-30 00:14 UTC, bassrock commented
@cyndichin ready for review, and added a CI step for the xcode build.

What do you think about merging this and then doing incremental updates when we align on more rules with the rest of the Mozilla org?

2022-08-30 00:15 UTC, bassrock commented on bitrise.yml
> +      - brew-install@0:
Adding swiftlint to the bitrise file.

2022-08-30 00:15 UTC, bassrock commented on setup_build_tools.sh
> +# Install all the required dependencies for building and deploying Pocket for iOS
A helper script to help new devs install required tools to build pocket.

2022-09-01 21:51 UTC, jacobsimeon requested changes
I'd love to have a conversation about this as team before we go ahead with the merge.

2022-09-06 20:57 UTC, jacobsimeon approved these changes

2022-09-06 20:59 UTC, merged