Fix test build failing
Pocket/pocket-ios pull request #446
Opened 2023-02-28 23:05 UTC by Gio2018

## Summary
* Include short description of what this PR accomplishes

## References 
* Links to docs, tickets, designs if available

## Implementation Details
* Overview of work that was implemented and changes made to the codebase

## Test Steps
* Write out what QA should do to verify this change works as expected and hasn't introduced regressions. Can mention specific OS versions, devices, areas of the app to test as needed.

## PR Checklist:
- [ ] Added Unit / UI tests
- [ ] Self Review (review, clean up, documentation, run tests)
- [ ] Basic Self QA

## Screenshots

2023-03-01 22:19 UTC, Gio2018 commented on PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
> +    static let shouldAllowUpgrade = true
Will revert this to `false` before merging, so beta testers will still see the "Coming Soon!" alert

2023-03-02 13:59 UTC, cyndichin commented on PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
> +class MockSubscriptionStore: SubscriptionStore {
nit: should we move this to its own file?

2023-03-02 14:03 UTC, cyndichin requested changes
looks good in terms of `SearchViewModelTests`! I am seeing this following error when running `SearchTests`.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/6743397/222450428-7b4099ee-d43c-4ee5-982b-cc237d2205fa.png">

2023-03-02 16:50 UTC, Gio2018 commented
Thanks for reviewing @cyndichin !!

> looks good in terms of `SearchViewModelTests`! I am seeing this following error when running `SearchTests`.
> <img alt="image" width="1004" src="https://user-images.githubusercontent.com/6743397/222450428-7b4099ee-d43c-4ee5-982b-cc237d2205fa.png">

I'm having a hard time reproducing this crash, can you please point me out to the code that causes it? Thank you!

2023-03-02 18:05 UTC, cyndichin approved these changes
thanks for fixing this issue! looks good :)

2023-03-02 18:11 UTC, Gio2018 commented
Thanks so much for the thorough review @cyndichin !!!

2023-03-02 18:11 UTC, merged